EMS-APP/routes/web.php
<?php

use App\Http\Controllers\AddNewEmployeeController;
use App\Http\Livewire\Crud;
use App\Http\Livewire\Admin\User;
use App\Http\Livewire\Admin\Profile;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MiniPosition;
use App\Http\Livewire\Admin\Dashboard;
use App\Http\Livewire\Admin\Department;
use App\Http\Controllers\AddNewPosition;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\LangController;
use App\Http\Livewire\Admin\crud as AdminCrud;
use App\Http\Livewire\Login as LoginComponent;
use App\Http\Controllers\MiniPositionController;
use App\Http\Livewire\User\Profile as UserProfile;
use App\Http\Livewire\Dasboard as DasboardComponent;
use App\Http\Livewire\User\Dashboard as UserDashboard;
use App\Http\Middleware\LanguageManager;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () {
//     return redirect()->route('login');
// });
route::get('/',DasboardComponent::class)->name('dashboard');
// Route::get('/', function () {
//     return view('welcome');
// });
// Route::resource('position', PositionController::class);

// Route::resource('department', DepartmentController::class);
// Route::get('{id}/edit', [departmentController::class,'edit'])->name('edit');
// Route::resource('products', ProductController::class);
// Route::resource('posts', PostController::class);

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

// for admin

Route::middleware(['auth:sanctum', 'verified','authadmin'])->group(function () {

    Route::get('/admin/dashboard',Dashboard::class)->name('admin.dashboard');
    Route::get('/admin/profile',Profile::class)->name('admin.profile.index');
    Route::get('/admin/user',User::class)->name('admin.user');
    // Route::get('/admin/department',department::class)->name('admin.department');
    // Route::resource('/admin/department',departmentController::class)->name('admin.department');
    // Route::get('/admin/department',[DepartmentController::class,'index'])->name('admin.department');
    // Route::post('/admin/department/store',[DepartmentController::class,'store'])->name('admin.department.store');
    // Route::post('/admin/department/delete',[DepartmentController::class,'destroy'])->name('admin.department.destroy');
        Route::resource('admin/department', DepartmentController::class);
    //tab
        Route::get('admin/department/{department}/home',[DepartmentController::class,'hometab']);
        Route::get('admin/department/{department}/employee',[DepartmentController::class,'employeetab']);
        Route::get('admin/department/{department}/position',[DepartmentController::class,'positiontab']);
    //position
        Route::resource('admin/position', PositionController::class);
    //employee
        Route::resource('admin/employee', EmployeeController::class);
    //department nest postion creation
        //create
            Route::get('/admin/department/{department}/postion/create',[AddNewPosition::class,'create'])->name('department.position.create');
        //store
            Route::post('/admin/department/{departments}',[AddNewPosition::class,'store'])->name('department.position.store');
        //show
            Route::get('/admin/department/{department}/position/{position}/show',[AddNewPosition::class,'show'])->name('department.position.show');
        //edit
            Route::get('/admin/department/{department}/position/{position}/edit',[AddNewPosition::class,'edit'])->name('department.position.edit');
        //update
            Route::put('admin/department/{departments}/position/{position}',[AddNewPosition::class,'update'])->name('department.position.update');
        //delete
            Route::delete('admin/department/{departments}/position/{position}',[AddNewPosition::class,'destroy'])->name('department.position.destroy');
    //department nest position nest employee creation
        //create
            Route::get('admin/department/{department}/position/{position}/show/employee/create',[AddNewEmployeeController::class,'create'])->name('department.position.employee.create');
        //store
            Route::post('/admin/department/{departments}',[AddNewPosition::class,'store'])->name('department.position.store');
        //show
            Route::get('/admin/department/{department}/position/{position}/show',[AddNewPosition::class,'show'])->name('department.position.show');
        //edit
            Route::get('/admin/department/{department}/position/{position}/edit',[AddNewPosition::class,'edit'])->name('department.position.edit');
        //update
            Route::put('admin/department/{departments}/position/{position}',[AddNewPosition::class,'update'])->name('department.position.update');
        //delete
            Route::delete('admin/department/{departments}/position/{position}',[AddNewPosition::class,'destroy'])->name('department.position.destroy');

 });
        //Route Laguage
            // Route::get('/',[LangController::class,'index']);
            route::get('/change',[DasboardComponent::class,'change'])->name('changelang');

// for user

Route::middleware(['auth:sanctum', 'verified','authuser'])->group(function () {

    Route::get('/user/dashboard',UserDashboard::class)->name('user.dashboard');
    Route::get('/user/profile',UserProfile::class)->name('user.profile');
    // Route::get('/admin/post',Profile::class)->name('admin.post');
    // Route::get('/admin/user',::class)->name('admin.user');

    });

EMS-APP/app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\Position;
use App\Models\Department;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search =  $request->input('search');
        if($search!=""){
            $employee= Employee::where(function ($query) use ($search){
                $query->where('name','like', '%'.$search.'%')
                    ->orWhere('email', 'like', '%'.$search.'%')
                    ->orWhere('cell_phone_number', 'like', '%'.$search.'%')
                    ->orWhere('position_id', 'like', '%'.$search.'%')
                    ;
            }
            )
            ->paginate(4);

            $employee->appends(['search' => $search]);
        }

        else{
            $employee = Employee::paginate(4);
        }
        return view('livewire.admin.employee',['employee'=>$employee,'search'=>$search]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $position=Position::all();
        return view('livewire.Employee.create',['position'=>$position]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            // 'user_id'=>'required',
            'position_id'=>'required',
            'name'=>'required',
            'gender'=>'required',
            'address'=>'required',
            'phone_number'=>'required',
            'cell_phone_number'=>'required',
            'email'=>'required',
            'dob'=>'required',
            'learning_institute'=>'required',
            'marital_status'=>'required',
            'description'=>'required',
            // 'Spouses_name',
            // 'Spouses_contact',
            'image'=>'required|mimes:png,jpg,jpeg|max:5048'
        ]);
        $newImagename=time(). '-'.$request->name.'.'.$request->image->extension();
        $request->image->move(public_path('Employee'),$newImagename);
        //    department::create($request->all());
        Employee::create([
            'user_id'=>$request->input('user_id'),
            'position_id'=>$request->input('position_id'),
            'name'=>$request->input('name'),
            'gender'=>$request->input('gender'),
            'address'=>$request->input('address'),
            'phone_number'=>$request->input('phone_number'),
            'cell_phone_number'=>$request->input('cell_phone_number'),
            'email'=>$request->input('email'),
            'dob'=>$request->input('dob'),
            'learning_institute'=>$request->input('learning_institute'),
            'marital_status'=>$request->input('marital_status'),
            'description'=>$request->input('description'),
            'Spouses_name'=>$request->input('Spouses_name'),
            'Spouses_contact'=>$request->input('Spouses_contact'),
            'image_path'=>$newImagename
        ]);
            return redirect()->route('employee.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        return view('livewire.Employee.show',['employee'=>$employee]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $position=Position::all();
        return view('livewire.employee.edit',['position'=>$position,'employee'=>$employee]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $request->validate([
            // 'user_id'=>'required',
            'position_id'=>'required',
            'name'=>'required',
            'gender'=>'required',
            'address'=>'required',
            'phone_number'=>'required',
            'cell_phone_number'=>'required',
            'email'=>'required',
            'dob'=>'required',
            'learning_institute'=>'required',
            'marital_status'=>'required',
            'description'=>'required',
            // 'Spouses_name',
            // 'Spouses_contact',
            // 'image'=>'required|mimes:png,jpg,jpeg|max:5048'
        ]);
        // $newImagename=time(). '-'.$request->name.'.'.$request->image->extension();
        // $request->image->move(public_path('Employee'),$newImagename);
        //    department::create($request->all());
        $input = $request->all();
        if ($image = $request->image) {
            // $destinationPath = 'image/';
            $newImagename = time(). '-'.$request->name.'.'.$request->image->extension();
            // $image->move($destinationPath, $profileImage);
            $input['image_path'] = $newImagename;
            $image->move(public_path('Employee'),$newImagename);
        }else{
            unset($input['image_path']);
        }
        // $employee->update([
        //     'user_id'=>$request->input('user_id'),
        //     'position_id'=>$request->input('position_id'),
        //     'name'=>$request->input('name'),
        //     'gender'=>$request->input('gender'),
        //     'address'=>$request->input('address'),
        //     'phone_number'=>$request->input('phone_number'),
        //     'cell_phone_number'=>$request->input('cell_phone_number'),
        //     'email'=>$request->input('email'),
        //     'dob'=>$request->input('dob'),
        //     'learning_institute'=>$request->input('learning_institute'),
        //     'marital_status'=>$request->input('marital_status'),
        //     'description'=>$request->input('description'),
        //     'Spouses_name'=>$request->input('Spouses_name'),
        //     'Spouses_contact'=>$request->input('Spouses_contact'),
        //     // 'image_path'=>$newImagename
        // ]);
        $employee->update($input);
                return redirect()->route('employee.index')
                        ->with('success','Employee updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();
        return redirect()->route('employee.index');
    }
}

EMS-APP/app/Http/Livewire/Admin/Dashboard.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use App\Models\Employee;
use App\Models\Department;
use Livewire\WithPagination;

class Dashboard extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public function render()
    {
        $users=User::count();
        $department=Department::count();
        $employee=Employee::count();
        // $panel=User::all();
        // dd($panel);
        return view('livewire.admin.dashboard',
        [
        'users'=>$users,
        'department'=>$department,
        'panel' => User::paginate(1),
        'employee'=>$employee
        ]
        )->layout('layouts.base');
    }
}

EMS-APP/app/Http/Livewire/Admin/Department.php
<?php
// <?php

namespace App\Http\Livewire\Admin;
use App\Models\Department as ModelsDepartment;
use Livewire\Component;

class Department extends Component
{
//         public $department,$description,$phone_num,$image_path;
//         public $isModalOpen = 0;
    public $department;
    public function render()
    {
        $this->department=ModelsDepartment::all();
        return view('livewire.admin.department')->layout('layouts.base');
    }
    // public function create()
    // {
    //     $this->resetCreateForm();
    //     $this->openModalPopover();
    // }
    // public function openModalPopover()
    // {
    //     $this->isModalOpen = true;
    // }

    // public function closeModalPopover()
    // {
    //     $this->isModalOpen = false;
    // }
    // private function resetCreateForm(){
    //     $this-> department= '';
    //     $this->description = '';
    //     $this->phone_num= '';
    // }

    // public function store()
    // {
    //     $this->validate([
    //         'department' => 'required',
    //         'description' => 'required',
    //         'phone_num' => 'required',
    //     ]);

    //   ModelsDepartment::updateOrCreate(['id' => $this->id], [
    //         'department' => $this->department,
    //         'description' => $this->description,
    //         'phone_num' => $this->phone_num,
    //     ]);

    //     session()->flash('message', $this->id ? 'department updated.' : 'department created.');
    //     $this->closeModalPopover();
    //     $this->resetCreateForm();
    // }
    // public function edit($id)
    // {
    //     $department = ModelsDepartment::findOrFail($id);
    //     $this->id = $id;
    //     $this->department =$department->department;
    //     $this->description=$department->description;
    //     $this->phone_num =$department->phone_num;
    //     $this->updateMode = true;
    //     $this->openModalPopover();
    // }

    // public function delete($id)
    // {
    //     ModelsDepartment::find($id)->delete();
    //     session()->flash('message', 'department deleted.');
    // }}
    }

EMS-APP/app/Http/Livewire/Admin/Employee.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class Employee extends Component
{
    public function render()
    {
        return view('livewire.admin.employee');
    }
}

EMS-APP/app/Http/Livewire/Admin/Position.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class Position extends Component
{
    public function render()
    {
        return view('livewire.admin.position')->layout('layouts.base');
    }
}

EMS-APP/app/Http/Livewire/Admin/Profile.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;

class Profile extends Component
{
    public function render()
    {
        return view('livewire.admin.profile')->layout('layouts.base');
    }
}

EMS-APP/app/Http/Livewire/Admin/Salary.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class Salary extends Component
{
    public function render()
    {
        return view('livewire.admin.salary');
    }
}

EMS-APP/app/Http/Livewire/Admin/User.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class User extends Component
{
    public function render()
    {
        return view('livewire.admin.user');
    }
}

EMS-APP/app/Http/Livewire/Login.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Login extends Component
{
    public function render()
    {
        return view('');
    }
}

EMS-APP/app/View/Components/BaseLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BaseLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.base');
    }
}

EMS-APP/resources/views/livewire/Employee/create.blade.php
<x-base-layout>
    @section('title','Add New Employee')
            <section class="section">
                    <h1 class="section-header">
                        {{-- @if ($updateMode) --}}
                        <div>Add New Employee</div>
                        {{-- @else --}}
                        {{-- <div>Setting employee</div> --}}
                        {{-- @endif --}}
                </h1>

                <div class="row">
                    <div class="col-lg-5 margin-tb">
                    </div>
                </div>

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                    <form action="{{ route('employee.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @include('livewire.admin.include.create-employee')

                    </form>
                </div>
            </section>
    @push('script')
    <!-- jQuery -->
    {{-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script> --}}
    <script>
        function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
            $('#imgPlaceholder').attr('src', e.target.result);
            }

            // base64 string conversion
            reader.readAsDataURL(input.files[0]);
        }
        }

        $("#chooseFile").change(function () {
        readURL(this);
        });

    $("input").on("change", function() {
            this.setAttribute(
                "data-date",
                moment(this.value, "YYYY-MM-DD")
                .format( this.getAttribute("data-date-format") )
            )
        }).trigger("change")
    </script>

    @endpush
</x-base-layout>

EMS-APP/resources/views/livewire/Employee/edit.blade.php
<x-base-layout>
    @section('title','Add New Employee')
    <section class="section">
            <h1 class="section-header">
                {{-- @if ($updateMode) --}}
                <div>Update Employee Info</div>
                {{-- @else --}}
                {{-- <div>Setting employee</div> --}}
                {{-- @endif --}}
        </h1>

<div class="row">
    <div class="col-lg-5 margin-tb">
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('employee.update',$employee['id']) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PUT')
     <div class="row">
         <div class="col-md-6">
            {{-- header --}}
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Position:</strong>
                    <select class="form-control" name="position_id">
                    <option class="d-none" value="{{ $employee->position_id }}">{{ $employee->position->department->department }} | {{ $employee->position->position }}</option>
                    @foreach ($position as $positions)
                    <option value="{{ $positions['id'] }}">{{ $positions['department']->department }} | {{ $positions['position']}}</option>
                    @endforeach
                    </select>
                </div>
            </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" value="{{ $employee['name'] }}" name="name" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4">
                <div class="form-group">
                    <strong>Gender:</strong>
                    <select class="form-control" name="gender">
                    <option class="d-none" value="{{ $employee['gender'] }}">{{ $employee['gender'] }}</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>

                    </select>
                </div>
            </div>
            </div>
        </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Date Of Birth:</strong>
                    <input id="date" type="date" data-date="" data-date-format="DD/MM/YYYY" value="{{ $employee['dob'] }}" name="dob" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Educational institution</strong>
                    <input type="text" value="{{ $employee['learning_institute'] }}" name="learning_institute" class="form-control" placeholder="Educational Institution">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <div class="form-group">
                        <strong>Marital Status</strong>
                        <select class="form-control" name="marital_status">
                        <option class="d-none" value="{{ $employee['marital_status'] }}">{{ $employee['marital_status'] }}</option>
                        <option value="Single">Single</option>
                        <option value="Married">Married</option>
                        <option value="Windowed">Windowed</option>
                        <option value="Divorced">Divorced</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                      <strong>Spouse's Name:</strong>
                      <input type="text" value="{{ $employee['Spouses_name'] }}" name="Spouses_name" class="form-control" placeholder="Spouse's Name (Optional)">
                  </div>
              </div>
              <div class="col-xs-6 col-sm-6 col-md-6">
                  <div class="form-group">
                      <strong>Spouse's Contact:</strong>
                      <input type="text" value="{{ $employee['Spouses_contact'] }}" name="Spouses_contact" class="form-control" placeholder="Spouse's Contact (Optional)">
                  </div>
              </div>
              </div>
                </div>


            <div class="col-xs-12 col-sm-12 col-md-12 mt-2">
                <div class="form-group">
                    <strong>Address</strong>
                    <textarea class="form-control" rows="3" name="address" placeholder="Address">{{ $employee['address'] }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 my-3">
                <a href="{{ route('employee.index') }}" class="btn btn-danger  btn-sm" role="button" data-toggle="tooltip" title="" data-original-title="Back"><i class="ion-arrow-left-a"></i></a>
            </div>

         </div>

         <div class="col-md-6">
        {{-- <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Image:</strong>
                <input type="file" name="image" class="form-control" placeholder="employee">
            </div>
        </div> --}}
        <div class="row d-flex justify-content-center">
            <div class="col-xs-9 col-sm-9 col-md-9 mb-3">
                <strong>Image:</strong>
                <div class="custom-file">
                    <input type="file"  name="image" value="{{ $employee['image_path']}}" class="custom-file-input" id="chooseFile">
                    <label class="custom-file-label" for="chooseFile">{{ $employee['image_path']}}</label>
                </div>
                <div class="user-image mt-3 text-center">
                    <div style="width: 300px; height: 300px; overflow: hidden; background: #cccccc; margin: 0 auto">
                        <img src="{{ URL::to('Employee/'.$employee['image_path']) }}" class="figure-img img-fluid rounded"  id="imgPlaceholder" alt="">
                    </div>
                  </div>

            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="row d-flex justify-content-center ">

                <div class="col-xs-10 col-sm-10 col-md-10">
                    <div class="form-group">
                        <strong>Description:</strong>
                        <textarea class="form-control" rows="1" name="description" placeholder="description">{{ $employee['description'] }}</textarea>
                    </div>
                </div>
                <div class="col-xs-10 col-sm-10 col-md-10">
                    <div class="form-group">
                        <strong>Email:</strong>
                        <input type='email' value="{{ $employee['email'] }}" name="email" class="form-control" placeholder="Email">
                    </div>
                </div>

                <div class="col-xs-5 col-sm-5 col-md-5">
                    <div class="form-group">
                        <strong>Phone Number:</strong>
                        <input type="text" value="{{ $employee['phone_number'] }}" name="phone_number" class="form-control" placeholder="Phone Number">
                    </div>
                </div>

                <div class="col-xs-5 col-sm-5 col-md-5">
                        <div class="form-group">
                            <strong>Cell Phone:</strong>
                            <input type="text" value="{{  $employee['cell_phone_number'] }}" name="cell_phone_number" class="form-control" placeholder="Cell Phone">
                        </div>
                </div>
            </div>
            <div class="form-group">
                <button type="Submit" class="btn btn-primary btn-sm float-right mr-5" role="button" data-toggle="tooltip" title="" data-original-title="update"><i class="ion-checkmark-circled"></i></button>
            </div>

        </div>
    </div>

</form>
</div>
</section>
@push('script')
<!-- jQuery -->
{{-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script> --}}
<script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
          $('#imgPlaceholder').attr('src', e.target.result);
        }

        // base64 string conversion
        reader.readAsDataURL(input.files[0]);
      }
    }

    $("#chooseFile").change(function () {
      readURL(this);
    });

$("input").on("change", function() {
        this.setAttribute(
            "data-date",
            moment(this.value, "YYYY-MM-DD")
            .format( this.getAttribute("data-date-format") )
        )
    }).trigger("change")
        </script>

@endpush
</x-base-layout>