EMS-APP/routes/web.php
<?php

use App\Http\Controllers\AddNewEmployeeController;
use App\Http\Livewire\Crud;
use App\Http\Livewire\Admin\User;
use App\Http\Livewire\Admin\Profile;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MiniPosition;
use App\Http\Livewire\Admin\Dashboard;
use App\Http\Livewire\Admin\Department;
use App\Http\Controllers\AddNewPosition;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\LangController;
use App\Http\Livewire\Admin\crud as AdminCrud;
use App\Http\Livewire\Login as LoginComponent;
use App\Http\Controllers\MiniPositionController;
use App\Http\Livewire\User\Profile as UserProfile;
use App\Http\Livewire\Dasboard as DasboardComponent;
use App\Http\Livewire\User\Dashboard as UserDashboard;
use App\Http\Middleware\LanguageManager;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () {
//     return redirect()->route('login');
// });
route::get('/',DasboardComponent::class)->name('dashboard');
// Route::get('/', function () {
//     return view('welcome');
// });
// Route::resource('position', PositionController::class);

// Route::resource('department', DepartmentController::class);
// Route::get('{id}/edit', [departmentController::class,'edit'])->name('edit');
// Route::resource('products', ProductController::class);
// Route::resource('posts', PostController::class);

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

// for admin

Route::middleware(['auth:sanctum', 'verified','authadmin'])->group(function () {

    Route::get('/admin/dashboard',Dashboard::class)->name('admin.dashboard');
    Route::get('/admin/profile',Profile::class)->name('admin.profile.index');
    Route::get('/admin/user',User::class)->name('admin.user');
    // Route::get('/admin/department',department::class)->name('admin.department');
    // Route::resource('/admin/department',departmentController::class)->name('admin.department');
    // Route::get('/admin/department',[DepartmentController::class,'index'])->name('admin.department');
    // Route::post('/admin/department/store',[DepartmentController::class,'store'])->name('admin.department.store');
    // Route::post('/admin/department/delete',[DepartmentController::class,'destroy'])->name('admin.department.destroy');
        Route::resource('admin/department', DepartmentController::class);
    //tab
        Route::get('admin/department/{department}/home',[DepartmentController::class,'hometab']);
        Route::get('admin/department/{department}/employee',[DepartmentController::class,'employeetab']);
        Route::get('admin/department/{department}/position',[DepartmentController::class,'positiontab']);
    //position
        Route::resource('admin/position', PositionController::class);
    //employee
        Route::resource('admin/employee', EmployeeController::class);
    //department nest postion creation
        //create
            Route::get('/admin/department/{department}/postion/create',[AddNewPosition::class,'create'])->name('department.position.create');
        //store
            Route::post('/admin/department/{departments}',[AddNewPosition::class,'store'])->name('department.position.store');
        //show
            Route::get('/admin/department/{department}/position/{position}/show',[AddNewPosition::class,'show'])->name('department.position.show');
        //edit
            Route::get('/admin/department/{department}/position/{position}/edit',[AddNewPosition::class,'edit'])->name('department.position.edit');
        //update
            Route::put('admin/department/{departments}/position/{position}',[AddNewPosition::class,'update'])->name('department.position.update');
        //delete
            Route::delete('admin/department/{departments}/position/{position}',[AddNewPosition::class,'destroy'])->name('department.position.destroy');
    //department nest position nest employee creation
        //create
            Route::get('admin/department/{department}/position/{position}/show/employee/create',[AddNewEmployeeController::class,'create'])->name('department.position.employee.create');
        //store
            Route::post('/admin/department/{departments}',[AddNewPosition::class,'store'])->name('department.position.store');
        //show
            Route::get('/admin/department/{department}/position/{position}/show',[AddNewPosition::class,'show'])->name('department.position.show');
        //edit
            Route::get('/admin/department/{department}/position/{position}/edit',[AddNewPosition::class,'edit'])->name('department.position.edit');
        //update
            Route::put('admin/department/{departments}/position/{position}',[AddNewPosition::class,'update'])->name('department.position.update');
        //delete
            Route::delete('admin/department/{departments}/position/{position}',[AddNewPosition::class,'destroy'])->name('department.position.destroy');

 });
        //Route Laguage
            // Route::get('/',[LangController::class,'index']);
            route::get('/change',[DasboardComponent::class,'change'])->name('changelang');

// for user

Route::middleware(['auth:sanctum', 'verified','authuser'])->group(function () {

    Route::get('/user/dashboard',UserDashboard::class)->name('user.dashboard');
    Route::get('/user/profile',UserProfile::class)->name('user.profile');
    // Route::get('/admin/post',Profile::class)->name('admin.post');
    // Route::get('/admin/user',::class)->name('admin.user');

    });

EMS-APP/app/Http/Livewire/Admin/Dashboard.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use App\Models\Employee;
use App\Models\Department;
use Livewire\WithPagination;

class Dashboard extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public function render()
    {
        $users=User::count();
        $department=Department::count();
        $employee=Employee::count();
        // $panel=User::all();
        // dd($panel);
        return view('livewire.admin.dashboard',
        [
        'users'=>$users,
        'department'=>$department,
        'panel' => User::paginate(1),
        'employee'=>$employee
        ]
        )->layout('layouts.base');
    }
}

EMS-APP/app/Http/Livewire/Admin/Department.php
<?php
// <?php

namespace App\Http\Livewire\Admin;
use App\Models\Department as ModelsDepartment;
use Livewire\Component;

class Department extends Component
{
//         public $department,$description,$phone_num,$image_path;
//         public $isModalOpen = 0;
    public $department;
    public function render()
    {
        $this->department=ModelsDepartment::all();
        return view('livewire.admin.department')->layout('layouts.base');
    }
    // public function create()
    // {
    //     $this->resetCreateForm();
    //     $this->openModalPopover();
    // }
    // public function openModalPopover()
    // {
    //     $this->isModalOpen = true;
    // }

    // public function closeModalPopover()
    // {
    //     $this->isModalOpen = false;
    // }
    // private function resetCreateForm(){
    //     $this-> department= '';
    //     $this->description = '';
    //     $this->phone_num= '';
    // }

    // public function store()
    // {
    //     $this->validate([
    //         'department' => 'required',
    //         'description' => 'required',
    //         'phone_num' => 'required',
    //     ]);

    //   ModelsDepartment::updateOrCreate(['id' => $this->id], [
    //         'department' => $this->department,
    //         'description' => $this->description,
    //         'phone_num' => $this->phone_num,
    //     ]);

    //     session()->flash('message', $this->id ? 'department updated.' : 'department created.');
    //     $this->closeModalPopover();
    //     $this->resetCreateForm();
    // }
    // public function edit($id)
    // {
    //     $department = ModelsDepartment::findOrFail($id);
    //     $this->id = $id;
    //     $this->department =$department->department;
    //     $this->description=$department->description;
    //     $this->phone_num =$department->phone_num;
    //     $this->updateMode = true;
    //     $this->openModalPopover();
    // }

    // public function delete($id)
    // {
    //     ModelsDepartment::find($id)->delete();
    //     session()->flash('message', 'department deleted.');
    // }}
    }

EMS-APP/app/Http/Livewire/Admin/Employee.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class Employee extends Component
{
    public function render()
    {
        return view('livewire.admin.employee');
    }
}

EMS-APP/app/Http/Livewire/Admin/Position.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class Position extends Component
{
    public function render()
    {
        return view('livewire.admin.position')->layout('layouts.base');
    }
}

EMS-APP/app/Http/Livewire/Admin/Profile.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;

class Profile extends Component
{
    public function render()
    {
        return view('livewire.admin.profile')->layout('layouts.base');
    }
}

EMS-APP/app/Http/Livewire/Admin/Salary.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class Salary extends Component
{
    public function render()
    {
        return view('livewire.admin.salary');
    }
}

EMS-APP/app/Http/Livewire/Admin/User.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;

class User extends Component
{
    public function render()
    {
        return view('livewire.admin.user');
    }
}

EMS-APP/app/Http/Livewire/Crud.php
<?php

namespace App\Http\Livewire;
use Livewire\Component;
use App\Models\Student;


class Crud extends Component
{
    public $students, $name, $email, $mobile, $student_id;
    public $isModalOpen = 0;

    public function render()
    {
        $this->students = Student::all();
        return view('livewire.crud');
    }

    public function create()
    {
        $this->resetCreateForm();
        $this->openModalPopover();
    }

    public function openModalPopover()
    {
        $this->isModalOpen = true;
    }

    public function closeModalPopover()
    {
        $this->isModalOpen = false;
    }

    private function resetCreateForm(){
        $this->name = '';
        $this->email = '';
        $this->mobile = '';
    }

    public function store()
    {
        $this->validate([
            'name' => 'required',
            'email' => 'required',
            'mobile' => 'required',
        ]);

        Student::updateOrCreate(['id' => $this->student_id], [
            'name' => $this->name,
            'email' => $this->email,
            'mobile' => $this->mobile,
        ]);

        session()->flash('message', $this->student_id ? 'Student updated.' : 'Student created.');

        $this->closeModalPopover();
        $this->resetCreateForm();
    }

    public function edit($id)
    {
        $student = Student::findOrFail($id);
        $this->student_id = $id;
        $this->name = $student->name;
        $this->email = $student->email;
        $this->mobile = $student->mobile;

        $this->openModalPopover();
    }

    public function delete($id)
    {
        Student::find($id)->delete();
        session()->flash('message', 'Studen deleted.');
    }
}

EMS-APP/app/Http/Livewire/Dasboard.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;
use App\Models\Employee;
use App\Models\Department;
use Illuminate\Http\Request;
use Livewire\WithPagination;
use Illuminate\Support\Facades\App;

class Dasboard extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';

    public function render()
    {
        $user=user::all();
        $users=User::count();
        $department=Department::count();
        $employee=Employee::count();
        return view('livewire.dasboard',[
            'user'=>$user,
            'users'=>$users,
            'department'=>$department,
            'panel' => User::paginate(1),
            'employee'=>$employee])->layout('layouts.guest');
    }
    public function change(Request $request)

    {
        App::setLocale($request->lang);

        session()->put('locale', $request->lang);

        return redirect()->back();

    }
}

EMS-APP/app/Http/Livewire/Login.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Login extends Component
{
    public function render()
    {
        return view('');
    }
}

EMS-APP/app/Http/Livewire/User/Dashboard.php
<?php

namespace App\Http\Livewire\User;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;
use Livewire\ComponentConcerns\RendersLivewireComponents;

class Dashboard extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public function render()
    {
        $users=User::count();
        // $panel=User::all();
        // dd($panel);
        return view('livewire.user.dashboard',['users'=>$users,
        'panel' => User::paginate(1)])->layout('layouts.base');
    }
}

EMS-APP/app/Http/Livewire/User/Department.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;

class Department extends Component
{
    public function render()
    {
        return view('livewire.user.department');
    }
}

EMS-APP/app/Http/Livewire/User/Employee.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;

class Employee extends Component
{
    public function render()
    {
        return view('livewire.user.employee');
    }
}

EMS-APP/app/Http/Livewire/User/Position.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;

class Position extends Component
{
    public function render()
    {
        return view('livewire.user.position');
    }
}

EMS-APP/app/Http/Livewire/User/Profile.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;

class Profile extends Component
{
    public function render()
    {
        return view('livewire.user.profile')->layout('layouts.base');
    }
}

EMS-APP/app/Http/Livewire/User/Salary.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;

class Salary extends Component
{
    public function render()
    {
        return view('livewire.user.salary');
    }
}

EMS-APP/app/View/Components/BaseLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BaseLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.base');
    }
}

EMS-APP/resources/views/livewire/admin/dashboard.blade.php
<div>
        @section('title', __('massages.Dashboard'))

              {{-- main-content --}}
                @include('include.main-content')
              {{-- end-main-content --}}

</div>

EMS-APP/resources/views/livewire/admin/department.blade.php
<x-base-layout>
<div>
    @section('title','All Department')

    <section class="section">
        @if (session()->has('message'))
            <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md my-3"
                role="alert">
                <div class="flex">
                    <div>
                        <p class="text-sm">{{ session('message') }}</p>
                    </div>
                </div>
            </div>
        @endif
            <h1 class="section-header">
                {{-- @if ($updateMode) --}}
                <div>All Department</div>
                {{-- @else --}}
                {{-- <div>Setting Department</div> --}}
                {{-- @endif --}}
        </h1>
        {{-- @if($isModalOpen) --}}
        {{-- @endif --}}
        <div class="section-body">
          <div class="row mt-5">
            <div class="col-12">
              <div class="card">
                <div class="card-header">

                  <div class="float-right">
                      {{-- SEARCH FUNCTION --}}
                    <form action="">
                      <div class="input-group">
                        <input type="text" id="myInput" name="search" value="{{ $search }}" class="form-control" placeholder="Search">
                        <div class="input-group-btn">
                          <button type="submit" id="myBtn" class="btn btn-secondary"><i class="ion ion-search"></i></button>
                        </div>
                      </div>
                    </form>
                    {{-- <form>
                        <input id="myInput" name="q" value="{{ $search }}" placeholder="Some text..">
                        <input type="submit" id="myBtn" value="Submit">
                    </form> --}}

                  </div>
                  <h4>Department List</h4>
                  <a href="{{ route('department.create') }}" class="btn btn-sm btn-primary ion-plus-circled"></a>

                </div>

                <div class="card-body">
                    {{-- <a href="#" wire:click="create()" type="button" class="btn btn-info btn-sm mb-2">Add New</a> --}}

                  <div class="table-responsive">
                    <div class="d-flex justify-content-end">
                    </div>
                    <table class="table table-striped">
                      <tbody>
                          <tr>
                        {{-- <th>ID</th> --}}
                        <th>Picture</th>
                        <th>Department</th>
                        <th>Members</th>
                        <th>Position</th>
                        {{-- <th>Contact</th> --}}
                        <th>Action</th>
                      </tr>
                      @foreach($department as $departments)
                      <tr>
                        {{-- <td>{{ $departments['id'] }}</td> --}}
                        <td>
                            <img alt="image" src="{{ asset('image/'.$departments['image_path']) }}" class="rounded-circle" width="35" data-toggle="title" title="Wildan Ahdian">
                        </td>

                        <td>
                            {{ $departments['department'] }}
                        </td>
                        <td>
                            @forelse ($departments->employee as $item )
                            <img alt="image" src="{{ asset('Employee/'.$item['image_path']) }}" class="rounded-circle" width="35" data-toggle="title" title="{{ $item->name }}">
                            @empty
                            none
                            @endforelse
                            </div>
                        </td>
                        <td>
                            <div class="badge badge-info">
                                {{ $departments->position->count() }}
                            </div>

                        </td>
                        {{-- <td>{{ $departments['phone_num'] }}</td> --}}
                        <td>
                            <form action="{{ route('department.destroy',$departments->id) }}" method="POST">
                                <a href=" {{ url('admin/department/'.$departments->id.'/home') }}" class="btn btn-success btn-action" data-toggle="tooltip" title="" data-original-title="view"><i class="fas fa-eye"></i></a>
                                <a href="{{ route('department.edit',$departments['id']) }}" class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="" data-original-title="Edit"><i class="ion ion-edit"></i></a>
                                {{-- <a href="{{ route('department.show',$departments['id']) }}" class="btn btn-success btn-action" data-toggle="tooltip" title="view"><i class="fas fa-eye"></i></a> --}}

                          @csrf
                          @method('DELETE')
                        {{-- <button type="submit" class="btn btn-danger">Delete</button> --}}
                <button class="btn btn-danger btn-action" data-toggle="tooltip" title="" data-original-title="Delete"><i class="ion ion-trash-b"></i></button>
                        </form>

                            {{-- <a class="btn btn-success btn-action" data-toggle="tooltip" title="" data-original-title="view"><i class="fas fa-eye"></i></a>
                            <a class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="" data-original-title="Edit"><i class="ion ion-edit"></i></a>
                            <a class="btn btn-danger btn-action" data-toggle="tooltip" title="" data-original-title="Delete"><i class="ion ion-trash-b"></i></a> --}}
                        </td>
                      </tr>
                        @endforeach
                    </tbody>
                </table>
                  </div>
                    <div class="d-flex justify-content-end">
                         {!! $department->links() !!}
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    <script>
        var input = document.getElementById("myInput");
        input.addEventListener("keyup", function(event) {
            if (event.keyCode === 13) {
                event.preventDefault();
                document.getElementById("myBtn").click();
            }
        });
    </script>
</x-base-layout>

EMS-APP/resources/views/livewire/admin/employee.blade.php
<x-base-layout>
    <div>
        @section('title','All Employee')

        <section class="section">
            @if (session()->has('message'))
                <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md my-3"
                    role="alert">
                    <div class="flex">
                        <div>
                            <p class="text-sm">{{ session('message') }}</p>
                        </div>
                    </div>
                </div>
            @endif
                <h1 class="section-header">
                    {{-- @if ($updateMode) --}}
                    <div>All Employee</div>
                    {{-- @else --}}
                    {{-- <div>Setting employee</div> --}}
                    {{-- @endif --}}
            </h1>
            {{-- @if($isModalOpen) --}}
            {{-- @endif --}}
            <div class="section-body">
              <div class="row mt-5">
                <div class="col-12">
                  <div class="card">
                    <div class="card-header">

                      <div class="float-right">
                          {{-- SEARCH FUNCTION --}}
                        <form action="">
                          <div class="input-group">
                            <input type="text" id="myInput" name="search" value="{{ $search }}" class="form-control" placeholder="Search">
                            <div class="input-group-btn">
                              <button type="submit" id="myBtn" class="btn btn-secondary"><i class="ion ion-search"></i></button>
                            </div>
                          </div>
                        </form>

                      </div>
                      <h4>Employee List</h4>
                      <a href="{{ route('employee.create') }}" class="btn btn-sm btn-primary ion-plus-circled"></a>
                    </div>

                    <div class="card-body">
                      <div class="table-responsive">
                        <div class="d-flex justify-content-end">
                        </div>
                        <table class="table table-striped">
                          <tbody>
                            <tr>
                            <th>ID</th>
                            <th>Profile</th>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Department</th>
                            {{-- <th>Description</th> --}}
                            {{-- <th>Status</th> --}}
                            <th>Contact</th>
                            <th>Action</th>

                          </tr>
                          @foreach($employee as $employees)
                          <tr>
                            <td>{{ $employees['id'] }}</td>
                            <td>
                                <div class="user-image mb-3 text-center">

                                    <div  style="width: 100px; height: 100px; overflow: hidden; background: #cccccc; margin: 0 auto;">
                                        <img  src="{{ URL::to('Employee/'.$employees['image_path']) }}" class="figure-img img-thumbnail"  id="imgPlaceholder" alt="">
                                    </div>

                              </div>

                                {{-- <img alt="image" src="{{ asset('Employee/'.$employees['image_path']) }}" class="rounded" width="75" data-toggle="title" title="Wildan Ahdian"> --}}
                              </td>

                            <td>
                                {{ $employees['name'] }}
                                {{-- {{ $departments['department'] }} --}}
                            </td>
                            <td>
                                {{ $employees['position']->position}}
                            </td>
                            {{-- <td>
                                <div class="badge badge-success">Allow</div>
                            </td> --}}
                            <td>{{ $employees['position']->department['department'] }}</td>

                            {{-- <td>{{ $employees['description']}}</td> --}}

                            <td>
                                {{$employees['email'] }}
                                <br>
                                {{$employees['cell_phone_number']}}
                            </td>
                            <td>
                                <form action="{{ route('employee.destroy',$employees->id) }}" method="POST">
                                    <a href=" {{route('employee.show',$employees['id'])}}" class="btn btn-success btn-action" data-toggle="tooltip" title="" data-original-title="view"><i class="fas fa-eye"></i></a>
                                    <a href="{{ route('employee.edit',$employees['id']) }}" class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="" data-original-title="Edit"><i class="ion ion-edit"></i></a>

                                    @csrf
                                    @method('DELETE')
                                 <button class="btn btn-danger btn-action" data-toggle="tooltip" title="" data-original-title="Delete"><i class="ion ion-trash-b"></i></button>
                                </form>
                            </td>

                          </tr>
                            @endforeach
                        </tbody>
                    </table>
                      </div>
                        <div class="d-flex justify-content-end">
                             {!! $employee->links() !!}
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </section>
        </div>
        <script>
            var input = document.getElementById("myInput");
            input.addEventListener("keyup", function(event) {
                if (event.keyCode === 13) {
                    event.preventDefault();
                    document.getElementById("myBtn").click();
                }
            });
        </script>
    </x-base-layout>

EMS-APP/resources/views/livewire/admin/salary.blade.php
<div>
    {{-- If your happiness depends on money, you will never be happy with yourself. --}}
</div>

EMS-APP/resources/views/livewire/admin/user.blade.php
<div>
<h1>User</h1>
</div>