EMS-APP/routes/web.php
<?php

use App\Http\Controllers\AddNewEmployeeController;
use App\Http\Livewire\Crud;
use App\Http\Livewire\Admin\User;
use App\Http\Livewire\Admin\Profile;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MiniPosition;
use App\Http\Livewire\Admin\Dashboard;
use App\Http\Livewire\Admin\Department;
use App\Http\Controllers\AddNewPosition;
use App\Http\Controllers\PostController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\LangController;
use App\Http\Livewire\Admin\crud as AdminCrud;
use App\Http\Livewire\Login as LoginComponent;
use App\Http\Controllers\MiniPositionController;
use App\Http\Livewire\User\Profile as UserProfile;
use App\Http\Livewire\Dasboard as DasboardComponent;
use App\Http\Livewire\User\Dashboard as UserDashboard;
use App\Http\Middleware\LanguageManager;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () {
//     return redirect()->route('login');
// });
route::get('/',DasboardComponent::class)->name('dashboard');
// Route::get('/', function () {
//     return view('welcome');
// });
// Route::resource('position', PositionController::class);

// Route::resource('department', DepartmentController::class);
// Route::get('{id}/edit', [departmentController::class,'edit'])->name('edit');
// Route::resource('products', ProductController::class);
// Route::resource('posts', PostController::class);

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

// for admin

Route::middleware(['auth:sanctum', 'verified','authadmin'])->group(function () {

    Route::get('/admin/dashboard',Dashboard::class)->name('admin.dashboard');
    Route::get('/admin/profile',Profile::class)->name('admin.profile.index');
    Route::get('/admin/user',User::class)->name('admin.user');
    // Route::get('/admin/department',department::class)->name('admin.department');
    // Route::resource('/admin/department',departmentController::class)->name('admin.department');
    // Route::get('/admin/department',[DepartmentController::class,'index'])->name('admin.department');
    // Route::post('/admin/department/store',[DepartmentController::class,'store'])->name('admin.department.store');
    // Route::post('/admin/department/delete',[DepartmentController::class,'destroy'])->name('admin.department.destroy');
        Route::resource('admin/department', DepartmentController::class);
    //tab
        Route::get('admin/department/{department}/home',[DepartmentController::class,'hometab']);
        Route::get('admin/department/{department}/employee',[DepartmentController::class,'employeetab']);
        Route::get('admin/department/{department}/position',[DepartmentController::class,'positiontab']);
    //position
        Route::resource('admin/position', PositionController::class);
    //employee
        Route::resource('admin/employee', EmployeeController::class);
    //department nest postion creation
        //create
            Route::get('/admin/department/{department}/postion/create',[AddNewPosition::class,'create'])->name('department.position.create');
        //store
            Route::post('/admin/department/{departments}',[AddNewPosition::class,'store'])->name('department.position.store');
        //show
            Route::get('/admin/department/{department}/position/{position}/show',[AddNewPosition::class,'show'])->name('department.position.show');
        //edit
            Route::get('/admin/department/{department}/position/{position}/edit',[AddNewPosition::class,'edit'])->name('department.position.edit');
        //update
            Route::put('admin/department/{departments}/position/{position}',[AddNewPosition::class,'update'])->name('department.position.update');
        //delete
            Route::delete('admin/department/{departments}/position/{position}',[AddNewPosition::class,'destroy'])->name('department.position.destroy');
    //department nest position nest employee creation
        //create
            Route::get('admin/department/{department}/position/{position}/show/employee/create',[AddNewEmployeeController::class,'create'])->name('department.position.employee.create');
        //store
            Route::post('/admin/department/{departments}',[AddNewPosition::class,'store'])->name('department.position.store');
        //show
            Route::get('/admin/department/{department}/position/{position}/show',[AddNewPosition::class,'show'])->name('department.position.show');
        //edit
            Route::get('/admin/department/{department}/position/{position}/edit',[AddNewPosition::class,'edit'])->name('department.position.edit');
        //update
            Route::put('admin/department/{departments}/position/{position}',[AddNewPosition::class,'update'])->name('department.position.update');
        //delete
            Route::delete('admin/department/{departments}/position/{position}',[AddNewPosition::class,'destroy'])->name('department.position.destroy');

 });
        //Route Laguage
            // Route::get('/',[LangController::class,'index']);
            route::get('/change',[DasboardComponent::class,'change'])->name('changelang');

// for user

Route::middleware(['auth:sanctum', 'verified','authuser'])->group(function () {

    Route::get('/user/dashboard',UserDashboard::class)->name('user.dashboard');
    Route::get('/user/profile',UserProfile::class)->name('user.profile');
    // Route::get('/admin/post',Profile::class)->name('admin.post');
    // Route::get('/admin/user',::class)->name('admin.user');

    });

EMS-APP/resources/views/include/department-table.blade.php
<div class="section-body">
    <div class="row mt-5">
      <div class="col-12">
        <div class="card">

          <div class="card-header">
            <div class="float-right">
              <form>
                <div class="input-group">
                  <input type="text" class="form-control" placeholder="Search">
                  <div class="input-group-btn">
                    <button class="btn btn-secondary"><i class="ion ion-search"></i></button>
                  </div>
                </div>
              </form>
            </div>
            <h4>Department List</h4>
          </div>
          <div class="card-body">
              {{-- <a href="#" wire:click="create()" type="button" class="btn btn-info btn-sm mb-2">Add New</a> --}}

            <div class="table-responsive">
              <div class="d-flex justify-content-end">
                  {{-- {!! $department->links() !!} --}}
              </div>
              <table class="table table-striped">
                <tbody>
                    <tr>
                  <th class="text-center">
                    <div class="custom-checkbox custom-control">
                      <input type="checkbox" data-checkboxes="mygroup" data-checkbox-role="dad" class="custom-control-input" id="checkbox-all">
                      <label for="checkbox-all" class="custom-control-label"></label>
                    </div>
                  </th>
                  <th>ID</th>
                  <th>Picture</th>
                  <th>Department</th>
                  <th>Description</th>
                  <th>Status</th>
                  <th>Contact</th>
                  <th>Action</th>
                </tr>
                @foreach($departments as $department)
                <tr>
                  <td width="40">
                    <div class="custom-checkbox custom-control">
                      <input type="checkbox" data-checkboxes="mygroup" class="custom-control-input" id="checkbox-1">
                      <label for="checkbox-1" class="custom-control-label"></label>
                    </div>
                  </td>
                  <td>{{ $department['id'] }}</td>
                  <td>
                      <img alt="image" src="{{ asset('image/'.$department['image_path']) }}" class="rounded-circle" width="35" data-toggle="title" title="Wildan Ahdian">
                    </td>

                  <td>
                      {{ $department['department'] }}
                  </td>
                  <td>{{ $department['description'] }}</td>
                  <td>
                      <div class="badge badge-success">Allow</div>
                  </td>
                  <td>{{ $department['phone_num'] }}</td>
                  <td>
                      <form action="{{ route('department.destroy',$department->id) }}" method="POST">
                          <a href="{{ route('department.edit',$department['id']) }}" class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="" data-original-title="Edit"><i class="ion ion-edit"></i></a>
                          {{-- <a href="{{ route('department.show',$departments['id']) }}" class="btn btn-success btn-action" data-toggle="tooltip" title="view"><i class="fas fa-eye"></i></a> --}}

                    @csrf
                    @method('DELETE')
                  {{-- <button type="submit" class="btn btn-danger">Delete</button> --}}
          <button class="btn btn-danger btn-action" data-toggle="tooltip" title="" data-original-title="Delete"><i class="ion ion-trash-b"></i></button>
                  </form>

                      {{-- <a class="btn btn-success btn-action" data-toggle="tooltip" title="" data-original-title="view"><i class="fas fa-eye"></i></a>
                      <a class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="" data-original-title="Edit"><i class="ion ion-edit"></i></a>
                      <a class="btn btn-danger btn-action" data-toggle="tooltip" title="" data-original-title="Delete"><i class="ion ion-trash-b"></i></a> --}}
                  </td>
                </tr>
                  @endforeach
              </tbody>
          </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

EMS-APP/resources/views/include/main-content.blade.php
    <section class="section">
      <h1 class="section-header">
        <div>{{ __('massages.Dashboard') }}</div>
      </h1>
      <div class="row d-flex justify-content-center">
        <div class="col-lg-4 col-md-6 col-12">
          <div class="card card-sm-3">
            <div class="card-icon bg-primary">
              <i class="ion ion-person"></i>
            </div>
            <div class="card-wrap">
              <div class="card-header">
                <h4>{{ __('massages.TOTAL USERS') }}</h4>
              </div>
              <div class="card-body">
                {{$users}}
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-4 col-md-6 col-12">
          <div class="card card-sm-3">
            <div class="card-icon bg-danger">
                <i class="fas fa-users"></i>
            </div>
            <div class="card-wrap">
              <div class="card-header">
                <h4>{{ __('massages.EMPLOYEE') }}</h4>
              </div>
              <div class="card-body">
                {{ $employee }}
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-6 col-12">
          <div class="card card-sm-3">
            <div class="card-icon bg-success">
                <i class="far fa-building"></i>
            </div>
            <div class="card-wrap">
              <div class="card-header">
                <h4>{{ __('massages.DEPARTMENT') }}</h4>
              </div>
              <div class="card-body">
                {{ $department }}
              </div>
            </div>
          </div>
        </div>
        {{-- <div class="col-lg-3 col-md-6 col-12">
            <div class="card card-sm-3">
              <div class="card-icon bg-warning">
                <i class="ion ion-paper-airplane"></i>
              </div>
              <div class="card-wrap">
                <div class="card-header">
                  <h4>Message</h4>
                </div>
                <div class="card-body">
                  0
                </div>
              </div>
            </div>
          </div> --}}

      </div>

      {{-- <div class="row">
        <div class="col-lg-8 col-md-12 col-12 col-sm-12">
          <div class="card">
            <div class="card-header">
              <div class="float-right">
                <div class="btn-group">
                  <a href="#" class="btn active">Week</a>
                  <a href="#" class="btn">Month</a>
                  <a href="#" class="btn">Year</a>
                </div>
              </div>
              <h4>Statistics</h4>
            </div>
            <div class="card-body">
              <canvas id="myChart" height="158"></canvas>
              <div class="statistic-details mt-sm-4">
                <div class="statistic-details-item">
                  <small class="text-muted"><span class="text-primary"><i class="ion-arrow-up-b"></i></span> 7%</small>
                  <div class="detail-value">$243</div>
                  <div class="detail-name">Today's Sales</div>
                </div>
                <div class="statistic-details-item">
                  <small class="text-muted"><span class="text-danger"><i class="ion-arrow-down-b"></i></span> 23%</small>
                  <div class="detail-value">$2,902</div>
                  <div class="detail-name">This Week's Sales</div>
                </div>
                <div class="statistic-details-item">
                  <small class="text-muted"><span class="text-primary"><i class="ion-arrow-up-b"></i></span>9%</small>
                  <div class="detail-value">$12,821</div>
                  <div class="detail-name">This Month's Sales</div>
                </div>
                <div class="statistic-details-item">
                  <small class="text-muted"><span class="text-primary"><i class="ion-arrow-up-b"></i></span> 19%</small>
                  <div class="detail-value">$92,142</div>
                  <div class="detail-name">This Year's Sales</div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-12 col-12 col-sm-12">
          <div class="card">
            <div class="card-header">
              <h4>Recent Activities</h4>
            </div>
            <div class="card-body">
              <ul class="list-unstyled list-unstyled-border">
                <li class="media">
                  <img class="mr-3 rounded-circle" width="50" src="../dist/img/avatar/avatar-1.jpeg" alt="avatar">
                  <div class="media-body">
                    <div class="float-right"><small>10m</small></div>
                    <div class="media-title">Farhan A Mujib</div>
                    <small>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin.</small>
                  </div>
                </li>
                <li class="media">
                  <img class="mr-3 rounded-circle" width="50" src="../dist/img/avatar/avatar-2.jpeg" alt="avatar">
                  <div class="media-body">
                    <div class="float-right"><small>10m</small></div>
                    <div class="media-title">Ujang Maman</div>
                    <small>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin.</small>
                  </div>
                </li>
                <li class="media">
                  <img class="mr-3 rounded-circle" width="50" src="../dist/img/avatar/avatar-3.jpeg" alt="avatar">
                  <div class="media-body">
                    <div class="float-right"><small>10m</small></div>
                    <div class="media-title">Rizal Fakhri</div>
                    <small>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin.</small>
                  </div>
                </li>
                <li class="media">
                  <img class="mr-3 rounded-circle" width="50" src="../dist/img/avatar/avatar-4.jpeg" alt="avatar">
                  <div class="media-body">
                    <div class="float-right"><small>10m</small></div>
                    <div class="media-title">Alfa Zulkarnain</div>
                    <small>Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin.</small>
                  </div>
                </li>
              </ul>
              <div class="text-center">
                <a href="#" class="btn btn-primary btn-round">
                  View All
                </a>
              </div>
            </div>
          </div>
        </div>
      </div> --}}
      <div class="row">
        {{-- <div class="col-lg-5 col-md-12 col-12 col-sm-12">
          <form method="post" class="needs-validation" novalidate="">
            <div class="card">
              <div class="card-header">
                <h4>Quick Draft</h4>
              </div>
              <div class="card-body">
                <div class="form-group">
                  <label>Title</label>
                  <input type="text" name="title" class="form-control" required>
                  <div class="invalid-feedback">
                    Please fill in the title
                  </div>
                </div>
                <div class="form-group">
                  <label>Content</label>
                  <textarea class="summernote-simple"></textarea>
                </div>
              </div>
              <div class="card-footer">
                <button class="btn btn-primary">Save Draft</button>
              </div>
            </div>
          </form>
        </div> --}}
        <div class="col-lg-12 col-md-12 col-12 col-sm-12">
          <div class="card">
            <div class="card-header">
              <div class="float-right">
                <nav class="d-inline-block">
                    {{-- <ul class="pagination mb-0">
                      <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1"><i class="ion ion-chevron-left"></i></a>
                      </li>
                      <li class="page-item active"><a class="page-link" href="#">1 <span class="sr-only">(current)</span></a></li>
                      <li class="page-item">
                        <a class="page-link" href="#">2</a>
                      </li>
                      <li class="page-item"><a class="page-link" href="#">3</a></li>
                      <li class="page-item">
                        <a class="page-link" href="#"><i class="ion ion-chevron-right"></i></a>
                      </li>
                    </ul> --}}
                    {{ $panel->links() }}

                  </nav>
                 </div>
              <h4>{{ __('massages.USERS PANNEL') }}</h4>
            </div>
            <div class="card-body text-center">
              <div class="table-responsive">
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th>N.O</th>
                      <th>Name</th>
                      <th>Role</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                      @foreach ($panel as $panels)
                      <tr>
                        <td>
                          {{ $panels['id'] }}
                        </td>
                        <td>
                          <a href="{{ url('admin/profile') }}"><img src="{{ asset('storage/'.Auth::user()->profile_photo_path) }}" alt="{{ Auth::user()->name }}" width="50" class="rounded-circle img-thumbnail mr-1">{{ $panels['name'] }}</a>
                        </td>
                        <td>
                          {{ $panels['user_type'] }}
                        </td>

                        <td>
                          <a class="btn btn-success btn-action" data-toggle="tooltip" title="view"><i class="fas fa-eye"></i></a>
                          <a class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit"><i class="ion ion-edit"></i></a>
                          <a class="btn btn-danger btn-action" data-toggle="tooltip" title="Delete"><i class="ion ion-trash-b"></i></a>
                        </td>
                      </tr>
                      @endforeach
                    {{-- <tr>
                      <td>
                        IT-01
                      </td>
                      <td>
                        <a href="#"><img src="../dist/img/avatar/avatar-1.jpeg" alt="avatar" width="30" class="rounded-circle mr-1"> Bagus Dwi Cahya</a>
                      </td>
                      <td>
                        Admin
                      </td>

                      <td>
                        <a class="btn btn-success btn-action" data-toggle="tooltip" title="view"><i class="fas fa-eye"></i></a>
                        <a class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit"><i class="ion ion-edit"></i></a>
                        <a class="btn btn-danger btn-action" data-toggle="tooltip" title="Delete"><i class="ion ion-trash-b"></i></a>
                      </td>
                    </tr>
                    <tr>
                      <td>
                        IT-02
                      </td>
                      <td>
                        <a href="#"><img src="../dist/img/avatar/avatar-1.jpeg" alt="avatar" width="30" class="rounded-circle mr-1"> Bagus Dwi Cahya</a>
                      </td>
                      <td>
                        Admin
                      </td>

                      <td>
                        <a class="btn btn-success btn-action" data-toggle="tooltip" title="view"><i class="fas fa-eye"></i></a>
                        <a class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit"><i class="ion ion-edit"></i></a>
                        <a class="btn btn-danger btn-action" data-toggle="tooltip" title="Delete"><i class="ion ion-trash-b"></i></a>
                      </td>
                    </tr> --}}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

EMS-APP/resources/views/include/main-sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
      <div class="sidebar-brand">
        <a href="{{ route('dashboard') }}">{{ __('massages.EMS') }}</a>
      </div>
      <div class="sidebar-user">
        <a href="{{ url('admin/profile') }}">
        <div class="sidebar-user-picture">
          <img alt="image" class="img-thumbnail" src="{{ asset('storage/'.Auth::user()->profile_photo_path) }}">
        </div>
        </a>
        <div class="sidebar-user-details">
          <div class="user-name">{{ Auth::user()->name }}</div>
          <div class="user-role">
            {{ Auth::user()->user_type }}
          </div>
        </div>
      </div>
      <ul class="sidebar-menu">
        <li class="menu-header">{{ __('massages.Dashboard') }}</li>
        <li class="{{ request()->is('admin/dashboard')? 'active' : '' }}">
          <a href="{{
          (Auth::user()->user_type==='admin')?
          route('admin.dashboard'):route('user.dashboard') }}">
          <i class="ion ion-speedometer"></i><span>{{ __('massages.Dashboard') }}</span></a>
        </li>

        <li class="menu-header">Management</li>
            <li>
                    <a href="#" class="has-dropdown"><i class="ion ion-person"></i>
                        <span>Users</span></a>
                    <ul class="menu-dropdown">
                    <li class="active"><a href=" {{route('admin.dashboard')}}"><i class="ion ion-ios-circle-outline"></i>User</a></li>
                    <li class="{{ request()->is('/admin/dashboard')? 'active' : '' }}"><a href="fontawesome.html"><i class="ion ion-ios-circle-outline"></i>Role</a></li>
                    <li class="{{ request()->is('/admin/dashboard')? 'active' : '' }}"><a href="flag.html"><i class="ion ion-ios-circle-outline"></i>Permision</a></li>
                    <li class="{{ request()->is('/admin/dashboard')? 'active' : '' }}"><a href="flag.html"><i class="ion ion-ios-circle-outline"></i>Add New</a></li>

                    </ul>
          </li>

          {{-- <li class="{{ request()->is( 'admin/employee')? 'active' : '' }}">
            <a href="#" class="has-dropdown"><i class="fas fa-users"></i><span>Employee</span></a>
            <ul class="menu-dropdown"> --}}
              {{-- <li><a href="flag.html"><i class="ion ion-ios-circle-outline"></i></a></li> --}}
              {{-- <li><a href="{{ request()->is( 'admin/employee/contact')? 'active' : '' }}"><i class="ion ion-ios-circle-outline"></i>Contact list</a></li> --}}

            {{-- </ul> --}}
          </li>

          <li class="{{ request()->is( 'admin/department')? 'active' : '' }}">
            <a href="{{
           route('department.index')
            }}">
            <i class="far fa-building"></i><span>Department</span></a>
          </li>
          <li class="{{ request()->is('admin/position')? 'active' : '' }}">
            <a href="{{
           route('position.index')
            }}">
            <i class="fas fa-book"></i><span>Position</span></a>
          </li>
          <li class="{{ request()->is( 'admin/employee')? 'active' : '' }}">
            <a href="
          {{ route('employee.index') }}
            ">
            <i class="fas fa-users"></i><span>Employee</span></a>
          </li>
        {{-- <li>
          <a href="#" class="has-dropdown"><i class="far fa-building"></i>
            <span>Department</span></a>
          <ul class="menu-dropdown">
            <li><a href="{{ route('department.index') }}"><i class="ion ion-ios-circle-outline"></i>Department</a></li>
            <li><a href="{{ route('position.index') }}"><i class="ion ion-ios-circle-outline"></i>Position</a></li>
          </ul>
        </li> --}}

      {{-- <li class="">
        <a href="" class="ml-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cash-coin mr-4" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
                <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
                <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
                <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
              </svg>
                <span>Salary</span>
            </a>
      </li> --}}

        <li class="menu-header">Contact & Notification</li>
        {{-- <li class="{{ request()->is( 'admin/employee')? 'active' : '' }}">
            <a href="
          {{ route('employee.index') }}
            ">
            <i class="ion ion-paper-airplane"></i><span>Massager</span></a>
          </li>
 --}}

    </aside>
  </div>